### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by Magauiya** [ryanxingql/winner-ntire22-vqe#1]
Dear authors,

Thank you for sharing a post about your solution. When are you planning to release your implementation and corresponding checkpoints?

**Comment by ryanxingql** [comment]
Hi Magauiya,
Thank you for being so interested.
This work is done during my internship at Alibaba. Due to the legal limitation, I have no right to release my implementation. Thus I detail the implementation in the blog.
If you have any questions, please get in touch with me.
If I am permitted to release the implementation, I will notify you here.

**Comment by ryanxingql** [comment]
Hi @Magauiya,

I get permission to release models. Sorry for being late.

Models: https://github.com/ryanxingql/winner-ntire22-vqe/releases/tag/v1.0
README: https://github.com/ryanxingql/winner-ntire22-vqe/blob/main/README_test.md
